version: '3.9'

services:
  postgres-intsance:
    image: postgres:13.6-bullseye
    restart: always
    container_name: postgres-instance
    hostname: postgres-instance
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - ./rabbitmq-data/:/var/lib/rabbitmq/
  iam:
    container_name: iam_container
    hostname: iam_host
    build: ./iam
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-instance:5432/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 10000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 30000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TEST_QUERY: SELECT 1
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: iam_schema
      SECURITY_JWT_EXPIRATION: 1440
      SECURITY_JWT_SECRET: 85FB6E819E9C3B340B3B225C53919F2A1E763B21BBA47F69481A17A3F7562CA0
      SECURITY_JWT_ISSUER: https://issuer-example.com
      SECURITY_JWT_AUDIENCE: https://audience-example.com
      CORS_ALLOWED_ORIGIN_LIST: "*"
      SPRING_FLYWAY_SCHEMAS: iam_schema
      SPRING_FLYWAY_CONNECT_RETRIES: 2
      SPRING_FLYWAY_CONNECT_RETRIES_INTERVAL: 30
      SPRING_FLYWAY_SQL_MIGRATION_PREFIX: V
      SPRING_FLYWAY_SQL_MIGRATION_SEPARATOR: __
      SPRING_FLYWAY_SQL_MIGRATION_SUFFIXES: .sql
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration      
      
      

